[package]
name = "otter-vm-bytecode"
version = "0.1.0"
edition = "2024"
description = "Bytecode format for Otter VM"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
parking_lot = { version = "0.12", features = ["serde"] }
thiserror.workspace = true
rustc-hash = "2.0"

[dev-dependencies]
